### ISSUE TITLE
Enhancement: Adjust to a range rather than a value

### ISSUE THREAD

**Issue by brownbat** [RisingOrange/Reset-Ease-Automatically#3]
Users might also want to bring their ease to a specified range.

So if they could set a deck to, say, 200-300 ease, it would take any card below 200 and raise it to 200, and any card above 300 and lower it to 300.

That would let ease values float a bit, but not get too crazy.

Not sure how much demand there would be for this, but might be easy to implement.

Just an idea, I'd wait for somebody to second this before prioritizing it.

**Comment by RisingOrange** [comment]
This is indeed easy to implement. The UI is clearly the hardest part here.
I think the easiest way to do this is to add a tolerance value to the preferences. (with tolerance 50 and target ease value 250 the range is 200-300). Then set the default tolerance to 0.

Unfortunately I'm also unsure how useful this would be.

**Comment by RisingOrange** [comment]
I added the functionality. Not by using tolerances, like described in my previous comment, but with normal ranges.
The new version is not yet on AnkiWeb (I will probably upload it there soon), so to try it one has to download it from here.

Thanks for the idea!

**Comment by brownbat** [comment]
Nice! I've been on the road so it's been hard to test or code, but I think it's a good add.
