### ISSUE TITLE
Failed to load plugin after installing and restarting Anki

### ISSUE THREAD

**Issue by kytrinyx** [RisingOrange/Reset-Ease-Automatically#5]
When I restarted Anki after installing the plugin, it gave me an error (output below).

I've disabled it for now (and can totally continue to manually reset the ease daily) so this is by no means an urgent problem.

Thanks for developing the plugin ❤️ 

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Reset Ease Automatically':
Traceback (most recent call last):
  File "aqt/addons.py", line 97, in loadAddons
  File "/Users/kytrinyx/Library/Application Support/Anki2/addons21/12081346/__init__.py", line 1, in <module>
    from aqt import gui_hooks, mw
ImportError: cannot import name 'gui_hooks' from 'aqt' (/Applications/Anki.app/Contents/MacOS/aqt/__init__.pyc)
```

"About Anki" says I've got the following:

```
Version 2.1.19 (3c8690ae)
Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
```

I've got multiple versions of Python installed, but I'm assuming Anki is checking which version it's actually using when it reports 3.8.0, not just stating a dependency requirement.

**Comment by RisingOrange** [comment]
This should fix it. I updated the addon on AnkiWeb.

**Comment by kytrinyx** [comment]
That was quick! This fixed it, and the plugin is doing exactly what it says on the tin. Thanks so much!
