### ISSUE TITLE
Unnecessary modifications to cards

### ISSUE THREAD

**Issue by nonodesu** [RisingOrange/Reset-Ease-Automatically#6]
The way the addon currently works is that the cards get modified even if they don't need to be, ie. when the ease is already within the desired parameters. This leads to unnecessary synchronization of thousands cards every day.
To solve this modify reset_ease.py and replace this code:
```
        for card_id in card_ids:
            card = mw.col.getCard(card_id)
            if card.factor < ease_min:
                card.factor = ease_min
            elif card.factor > ease_max:
                card.factor = ease_max
            card.flush()
```
with the following:
```
        for card_id in card_ids:
            card = mw.col.getCard(card_id)
            if card.factor < ease_min:
                card.factor = ease_min
                card.flush()
            elif card.factor > ease_max:
                card.factor = ease_max
                card.flush()
```
I don't know what card.flush() does _exactly_, I'd assume it changes the card's modification date even when there were no actual changes, and that forces synchronization of all cards in the affected collection.

**Comment by RisingOrange** [comment]
Done. Thanks for pointing this out!
